# Generated by Django 4.2 on 2024-09-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
        migrations.AddField(
            model_name='employee',
            name='accountno',
            field=models.CharField(default='0000000000', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.CharField(default='default@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='employee',
            table='onlinebanking',
        ),
    ]
