# Generated by Django 4.2 on 2024-09-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_remove_employee_password_employee_accountno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.AddField(
            model_name='employee',
            name='emailid',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='accountno',
            field=models.IntegerField(),
        ),
    ]
