# Generated by Django 4.2 on 2024-09-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_remove_employee_email_employee_emailid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emailid',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
